services:
  db:
    image: postgres:14
    container_name: my-postgres
    environment:
      - POSTGRES_USER=liuhaochen
      - POSTGRES_PASSWORD=110799
      - POSTGRES_DB=dota2
    ports:
      - "6000:5432"
    volumes:
      - psql:/var/lib/postgresql/data
    networks:
      - dota-pred
  
  test-db:
    image: postgres:14
    container_name: db-test
    environment:
      - POSTGRES_USER=liuhaochen
      - POSTGRES_PASSWORD=110799
      - POSTGRES_DB=dota2
    ports:
      - "6006:5432"
    volumes:
      - psql-test:/var/lib/postgresql/data
    networks:
      - dota-pred
  
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6380:6379"
    volumes:
      - redis:/data
    networks:
      - dota-pred
    
  test-redis:
    image: redis:latest
    container_name: redis-test
    ports:
      - "6390:6379"
    volumes:
      - redis-test:/data
    networks:
      - dota-pred
    profiles:
      - test
    
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-web
    environment:
      - PGADMIN_DEFAULT_EMAIL=liu_hao_chen@hotmail.com
      - PGADMIN_DEFAULT_PASSWORD=Password12345!
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - dota-pred
    depends_on:
      - test-db

  bentoml:
    container_name: model-server
    image: match_prediction:latest
    ports: 
      - "3333:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - dota-pred
  # app:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   container_name: my-app
  #   environment:
  #     - PYTHONPATH=/app
  #     - PREFECT_API_KEY=pnu_840CPoLQS29FPKDOKdzmpG8qeltPlj2GPTvp
  #     - PREFECT_API_URL=https://api.prefect.cloud/api/accounts/0e59c550-4bb3-4bf2-9d0d-af300c4e4428/workspaces/0d5682bd-eb2d-4b4b-9192-ba58ba741461
  #     - DATABASE_URL=postgresql://liuhaochen:110799@db:5432/dota2
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./backend:/app  # Local code is mapped for development purposes
  #   networks:
  #     - dota-pred

networks:
  dota-pred:
    driver: bridge

volumes:
  psql:
  psql-test:
  redis:
  redis-test:
  pgadmin-data:
  backend:    # Unused for now, but can be used later
