services:
  # Infrastructure services
  db:
    image: postgres:14
    container_name: my-postgres
    env_file: ./.env
    ports:
      - "6000:5432"
    volumes:
      - psql:/var/lib/postgresql/data
    networks:
      - dota-pred
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6380:6379"
    volumes:
      - redis:/data
    networks:
      - dota-pred
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5


  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-web
    env_file: ./.env
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - dota-pred
      - shared-caddy-network
    depends_on:
      db:
        condition: service_healthy
        restart: true


  prefect-server:
    image: prefecthq/prefect:3-latest
    container_name: prefect-server
    restart: always
    command: prefect server start --host 0.0.0.0
    env_file: ./.env
    depends_on:
      db:
        condition: service_healthy
        restart: true
    volumes:
      - ~/.prefect/storage:/root/.prefect/storage
    networks:
      - dota-pred
      - shared-caddy-network

  # Microservices
  api-service:
    build:
      context: .
      dockerfile: ./services/api_service/Dockerfile
    container_name: api-service
    ports:
      - "8000:8000"
    env_file: ./.env
    depends_on:
      - db
      - redis
    networks:
      - dota-pred

  live-orchestrator-app:
    build:
      context: .
      dockerfile: ./live_orchestrator_app/Dockerfile
    container_name: live-orchestrator-app
    env_file: ./.env
    depends_on:
      prefect-server:
        condition: service_started
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      loki:
        condition: service_healthy
    networks:
      - dota-pred

  dota-oracle-schedules:
    build:
      context: .
      dockerfile: ./dota_oracle_schedules/Dockerfile
    container_name: dota-oracle-schedules
    env_file: ./.env
    depends_on:
      prefect-server:
        condition: service_started
      db:
        condition: service_healthy
      loki:
        condition: service_healthy
    volumes:
      - ~/.prefect/storage:/root/.prefect/storage
    networks:
      - dota-pred


  # Logging and Observability
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - dota-pred
    healthcheck:
      # Checks Loki's /ready endpoint to ensure it's ready to receive logs.
      test: ["CMD-SHELL", "wget -q --spider http://localhost:3100/ready"]
      interval: 10s
      timeout: 5s
      retries: 5

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    depends_on:
      - loki
    networks:
      - dota-pred
      - shared-caddy-network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5


networks:
  dota-pred:
    driver: bridge
  shared-caddy-network:
    external: true

volumes:
  psql:
  redis:
  pgadmin-data:
  backend:    # Unused for now, but can be used later
