"""refactor table models

Revision ID: 108a45b0cd5e
Revises: 90573f54f27b
Create Date: 2025-06-01 01:48:09.883774

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "108a45b0cd5e"
down_revision: Union[str, None] = "90573f54f27b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("hero_features_match_id_fkey", "hero_features", type_="foreignkey")
    op.create_foreign_key(None, "hero_features", "matches", ["match_id"], ["match_id"])
    op.alter_column(
        "match_predictions", "prediction_date", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False
    )
    op.drop_constraint("player_hero_features_match_id_fkey", "player_hero_features", type_="foreignkey")
    op.create_foreign_key(None, "player_hero_features", "matches", ["match_id"], ["match_id"])
    op.drop_constraint("team_features_match_id_fkey", "team_features", type_="foreignkey")
    op.create_foreign_key(None, "team_features", "matches", ["match_id"], ["match_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "team_features", type_="foreignkey")  # type: ignore[arg-type]
    op.create_foreign_key(
        "team_features_match_id_fkey", "team_features", "matches", ["match_id"], ["match_id"], ondelete="CASCADE"
    )
    op.drop_constraint(None, "player_hero_features", type_="foreignkey")  # type: ignore[arg-type]
    op.create_foreign_key(
        "player_hero_features_match_id_fkey",
        "player_hero_features",
        "matches",
        ["match_id"],
        ["match_id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "match_predictions", "prediction_date", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True
    )
    op.drop_constraint(None, "hero_features", type_="foreignkey")  # type: ignore[arg-type]
    op.create_foreign_key(
        "hero_features_match_id_fkey", "hero_features", "matches", ["match_id"], ["match_id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###
