"""update: stored mapped_hero_id (str) instead of raw hero_id (int)

Revision ID: 13e5d0e36900
Revises: 64e70bb4b835
Create Date: 2025-05-20 00:33:44.889246

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "13e5d0e36900"
down_revision: Union[str, None] = "64e70bb4b835"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("leaguetable", "leagueid", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_column("leaguetable", "league_id")
    op.drop_constraint("fk_match_outcomes_match_id", "match_outcomes", type_="foreignkey")
    op.alter_column("match_predictions", "prediction", existing_type=sa.BOOLEAN(), nullable=True)
    op.drop_constraint("fk_match_predictions_match_id", "match_predictions", type_="foreignkey")
    op.alter_column(
        "matches",
        "slot_0_hero_id",
        existing_type=sa.INTEGER(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.alter_column(
        "matches",
        "slot_1_hero_id",
        existing_type=sa.INTEGER(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.alter_column(
        "matches",
        "slot_2_hero_id",
        existing_type=sa.INTEGER(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.alter_column(
        "matches",
        "slot_3_hero_id",
        existing_type=sa.INTEGER(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.alter_column(
        "matches",
        "slot_4_hero_id",
        existing_type=sa.INTEGER(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.alter_column(
        "matches",
        "slot_128_hero_id",
        existing_type=sa.INTEGER(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.alter_column(
        "matches",
        "slot_129_hero_id",
        existing_type=sa.INTEGER(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.alter_column(
        "matches",
        "slot_130_hero_id",
        existing_type=sa.INTEGER(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.alter_column(
        "matches",
        "slot_131_hero_id",
        existing_type=sa.INTEGER(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.alter_column(
        "matches",
        "slot_132_hero_id",
        existing_type=sa.INTEGER(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.alter_column("player_hero_histories", "win", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "player_hero_histories", "start_time", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False
    )
    op.alter_column("team_histories", "win", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("team_histories", "start_time", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False)
    op.alter_column("team_matchup_histories", "win", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "team_matchup_histories", "start_time", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "team_matchup_histories", "start_time", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True
    )
    op.alter_column("team_matchup_histories", "win", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("team_histories", "start_time", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True)
    op.alter_column("team_histories", "win", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "player_hero_histories", "start_time", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True
    )
    op.alter_column("player_hero_histories", "win", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "matches",
        "slot_132_hero_id",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "matches",
        "slot_131_hero_id",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "matches",
        "slot_130_hero_id",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "matches",
        "slot_129_hero_id",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "matches",
        "slot_128_hero_id",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "matches",
        "slot_4_hero_id",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "matches",
        "slot_3_hero_id",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "matches",
        "slot_2_hero_id",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "matches",
        "slot_1_hero_id",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "matches",
        "slot_0_hero_id",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.create_foreign_key("fk_match_predictions_match_id", "match_predictions", "matches", ["match_id"], ["match_id"])
    op.alter_column("match_predictions", "prediction", existing_type=sa.BOOLEAN(), nullable=False)
    op.create_foreign_key("fk_match_outcomes_match_id", "match_outcomes", "matches", ["match_id"], ["match_id"])
    op.add_column("leaguetable", sa.Column("league_id", sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column("leaguetable", "leagueid", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    # ### end Alembic commands ###
