"""Add league foreign key to matches and relationships

Revision ID: 251d60043abf
Revises: 270b527cfc53
Create Date: 2025-09-04 03:06:16.535256

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "251d60043abf"
down_revision: Union[str, None] = "270b527cfc53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key("fk_matches_leagueid_leaguetable", "matches", "leaguetable", ["leagueid"], ["leagueid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_matches_leagueid_leaguetable", "matches", type_="foreignkey")
    # ### end Alembic commands ###
