"""add img and icon url to heroData table

Revision ID: 270b527cfc53
Revises: 4b9c9623c957
Create Date: 2025-08-27 09:40:13.401151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '270b527cfc53'
down_revision: Union[str, None] = '4b9c9623c957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patch_number', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patches_patch_number'), 'patches', ['patch_number'], unique=True)
    op.add_column('herodatatable', sa.Column('img', sa.String(), nullable=True))
    op.add_column('herodatatable', sa.Column('icon', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('herodatatable', 'icon')
    op.drop_column('herodatatable', 'img')
    op.drop_index(op.f('ix_patches_patch_number'), table_name='patches')
    op.drop_table('patches')
    # ### end Alembic commands ###
