"""aded leagueid to MatchTable

Revision ID: 27d2c9fe590a
Revises: 13e5d0e36900
Create Date: 2025-05-28 11:55:59.024113

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "27d2c9fe590a"
down_revision: Union[str, None] = "13e5d0e36900"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("matches", sa.Column("leagueid", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("matches", "leagueid")
    # ### end Alembic commands ###
