"""Changed model_name in MatchPrediction to name to avoid naming conflict with protected namespace

Revision ID: 3c1102fc4b5c
Revises: 4c7dfd4c1ab2
Create Date: 2025-04-22 03:11:59.094102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3c1102fc4b5c'
down_revision: Union[str, None] = '4c7dfd4c1ab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pro_matches', 'radiant_name',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('pro_matches', 'dire_name',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('pro_matches', 'start_time',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('pro_matches', 'duration',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_match_id_constraint', 'pro_matches', ['match_id'])
    op.alter_column('pro_matches', 'duration',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('pro_matches', 'start_time',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('pro_matches', 'dire_name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('pro_matches', 'radiant_name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
