"""add unique constraint for team_matchup_history

Revision ID: 4b9c9623c957
Revises: 0f7016b9636d
Create Date: 2025-08-08 09:08:33.802064

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "4b9c9623c957"
down_revision: Union[str, None] = "0f7016b9636d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_constraint("team_matchup_histories_pkey", "team_matchup_histories", type_="primary")
    op.create_primary_key(
        "pk_team_matchup_histories",  # A name for the new constraint
        "team_matchup_histories",  # The table to modify
        ["team1_name", "team2_name", "match_id"],  # The columns in the key
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("pk_team_matchup_histories_composite", "team_matchup_histories", type_="primary")
    op.drop_constraint(
        "pk_team_matchup_histories",  # The name of the constraint to drop
        "team_matchup_histories",  # The table to modify
        type_="primary",  # The type of constraint
    )
    # ### end Alembic commands ###
