"""Changed hero and account id prefixes from c to slot_

Revision ID: 4c7dfd4c1ab2
Revises: ac9fd55058d7
Create Date: 2025-04-18 05:56:29.510982

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "4c7dfd4c1ab2"
down_revision: Union[str, None] = "ac9fd55058d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. First, copy data from old columns to new columns
    for old, new in [
        ("0_hero_id", "slot_0_hero_id"),
        ("1_hero_id", "slot_1_hero_id"),
        ("2_hero_id", "slot_2_hero_id"),
        ("3_hero_id", "slot_3_hero_id"),
        ("4_hero_id", "slot_4_hero_id"),
        ("128_hero_id", "slot_128_hero_id"),
        ("129_hero_id", "slot_129_hero_id"),
        ("130_hero_id", "slot_130_hero_id"),
        ("131_hero_id", "slot_131_hero_id"),
        ("132_hero_id", "slot_132_hero_id"),
        ("0_account_id", "slot_0_account_id"),
        ("1_account_id", "slot_1_account_id"),
        ("2_account_id", "slot_2_account_id"),
        ("3_account_id", "slot_3_account_id"),
        ("4_account_id", "slot_4_account_id"),
        ("128_account_id", "slot_128_account_id"),
        ("129_account_id", "slot_129_account_id"),
        ("130_account_id", "slot_130_account_id"),
        ("131_account_id", "slot_131_account_id"),
        ("132_account_id", "slot_132_account_id"),
    ]:
        # First create the new column
        op.add_column("pro_matches", sa.Column(new, sa.Float(), nullable=True))

        # Then copy data from old to new
        op.execute(f'UPDATE pro_matches SET {new} = "{old}"')

    # 2. After data is copied, drop old columns
    columns_to_drop = [
        "0_hero_id",
        "1_hero_id",
        "2_hero_id",
        "3_hero_id",
        "4_hero_id",
        "128_hero_id",
        "129_hero_id",
        "130_hero_id",
        "131_hero_id",
        "132_hero_id",
        "0_account_id",
        "1_account_id",
        "2_account_id",
        "3_account_id",
        "4_account_id",
        "128_account_id",
        "129_account_id",
        "130_account_id",
        "131_account_id",
        "132_account_id",
    ]

    for column in columns_to_drop:
        op.drop_column("pro_matches", column)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pro_matches", sa.Column("0_account_id", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.add_column(
        "pro_matches", sa.Column("1_hero_id", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.add_column(
        "pro_matches",
        sa.Column("128_account_id", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    )
    op.add_column(
        "pro_matches",
        sa.Column("130_account_id", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    )
    op.add_column(
        "pro_matches", sa.Column("0_hero_id", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.add_column(
        "pro_matches", sa.Column("128_hero_id", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.add_column(
        "pro_matches", sa.Column("2_hero_id", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.add_column(
        "pro_matches", sa.Column("130_hero_id", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.add_column(
        "pro_matches", sa.Column("129_hero_id", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.add_column(
        "pro_matches", sa.Column("132_hero_id", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.add_column(
        "pro_matches", sa.Column("3_hero_id", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.add_column(
        "pro_matches", sa.Column("131_hero_id", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.add_column(
        "pro_matches", sa.Column("1_account_id", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.add_column(
        "pro_matches",
        sa.Column("132_account_id", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    )
    op.add_column(
        "pro_matches",
        sa.Column("129_account_id", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    )
    op.add_column(
        "pro_matches", sa.Column("2_account_id", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.add_column(
        "pro_matches", sa.Column("3_account_id", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.add_column(
        "pro_matches",
        sa.Column("131_account_id", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    )
    op.add_column(
        "pro_matches", sa.Column("4_hero_id", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.add_column(
        "pro_matches", sa.Column("4_account_id", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.create_unique_constraint("unique_match_id_constraint", "pro_matches", ["match_id"])
    op.alter_column("pro_matches", "duration", existing_type=sa.Float(), type_=sa.BIGINT(), existing_nullable=True)
    op.alter_column("pro_matches", "start_time", existing_type=sa.Float(), type_=sa.BIGINT(), existing_nullable=True)
    op.alter_column(
        "pro_matches",
        "dire_name",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "pro_matches",
        "radiant_name",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.drop_column("pro_matches", "slot_132_account_id")
    op.drop_column("pro_matches", "slot_131_account_id")
    op.drop_column("pro_matches", "slot_130_account_id")
    op.drop_column("pro_matches", "slot_129_account_id")
    op.drop_column("pro_matches", "slot_128_account_id")
    op.drop_column("pro_matches", "slot_4_account_id")
    op.drop_column("pro_matches", "slot_3_account_id")
    op.drop_column("pro_matches", "slot_2_account_id")
    op.drop_column("pro_matches", "slot_1_account_id")
    op.drop_column("pro_matches", "slot_0_account_id")
    op.drop_column("pro_matches", "slot_132_hero_id")
    op.drop_column("pro_matches", "slot_131_hero_id")
    op.drop_column("pro_matches", "slot_130_hero_id")
    op.drop_column("pro_matches", "slot_129_hero_id")
    op.drop_column("pro_matches", "slot_128_hero_id")
    op.drop_column("pro_matches", "slot_4_hero_id")
    op.drop_column("pro_matches", "slot_3_hero_id")
    op.drop_column("pro_matches", "slot_2_hero_id")
    op.drop_column("pro_matches", "slot_1_hero_id")
    op.drop_column("pro_matches", "slot_0_hero_id")
    # ### end Alembic commands ###
