"""changed radiant_win field in MatchOutcome to accept optional values

Revision ID: 560282e4c798
Revises: bb8cf55dfcc3
Create Date: 2025-04-23 10:18:21.953402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '560282e4c798'
down_revision: Union[str, None] = 'bb8cf55dfcc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match_outcomes', 'radiant_win',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match_outcomes', 'radiant_win',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
