"""add match_id boundaries field in patch table

Revision ID: 5d3d6f960198
Revises: a431fe3a81a0
Create Date: 2025-09-24 07:51:18.711600

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5d3d6f960198"
down_revision: Union[str, None] = "a431fe3a81a0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("patches", sa.Column("start_match_id", sa.BigInteger(), nullable=True))
    op.add_column("patches", sa.Column("end_match_id", sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("patches", "end_match_id")
    op.drop_column("patches", "start_match_id")
    # ### end Alembic commands ###
