"""Added PlayerHeroFeature table

Revision ID: 677e4c99eee5
Revises: 8a4eea8fbd0e
Create Date: 2025-04-05 05:09:54.261115

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "677e4c99eee5"
down_revision: Union[str, None] = "8a4eea8fbd0e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "playerherofeature",
        sa.Column("match_id", sa.BigInteger(), nullable=False),
        sa.Column("player_hero_0_win_rate", sa.Float(), nullable=False),
        sa.Column("player_hero_1_win_rate", sa.Float(), nullable=False),
        sa.Column("player_hero_2_win_rate", sa.Float(), nullable=False),
        sa.Column("player_hero_3_win_rate", sa.Float(), nullable=False),
        sa.Column("player_hero_4_win_rate", sa.Float(), nullable=False),
        sa.Column("player_hero_128_win_rate", sa.Float(), nullable=False),
        sa.Column("player_hero_129_win_rate", sa.Float(), nullable=False),
        sa.Column("player_hero_130_win_rate", sa.Float(), nullable=False),
        sa.Column("player_hero_131_win_rate", sa.Float(), nullable=False),
        sa.Column("player_hero_132_win_rate", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["pro_matches.match_id"],
        ),
        sa.PrimaryKeyConstraint("match_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("playerherofeature")
    # ### end Alembic commands ###
