"""add 1-M relationship between matchtable and matchpredictiontable

Revision ID: 6a5fc8e63556
Revises: d582735221b4
Create Date: 2025-06-01 02:25:20.643749

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "6a5fc8e63556"
down_revision: Union[str, None] = "d582735221b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "match_predictions", "matches", ["match_id"], ["match_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "match_predictions", type_="foreignkey")  # type: ignore[arg-type]
    # ### end Alembic commands ###
