"""Added Hero and League data tables, Modified Table design of Histories table from storing a JSON of match histories, to storing the outcome for each combination key

Revision ID: 6f1ee7bbbedb
Revises: 560282e4c798
Create Date: 2025-05-01 08:47:10.722693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6f1ee7bbbedb'
down_revision: Union[str, None] = '560282e4c798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('herodatatable',
    sa.Column('primary_attr', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('agi_gain', sa.Float(), nullable=True),
    sa.Column('base_agi', sa.Float(), nullable=True),
    sa.Column('int_gain', sa.Float(), nullable=True),
    sa.Column('base_int', sa.Float(), nullable=True),
    sa.Column('str_gain', sa.Float(), nullable=True),
    sa.Column('base_str', sa.Float(), nullable=True),
    sa.Column('attack_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attack_rate', sa.Float(), nullable=True),
    sa.Column('attack_range', sa.Float(), nullable=True),
    sa.Column('attack_point', sa.Float(), nullable=True),
    sa.Column('projectile_speed', sa.Float(), nullable=True),
    sa.Column('base_armor', sa.Float(), nullable=True),
    sa.Column('base_mana', sa.Integer(), nullable=True),
    sa.Column('base_mana_regen', sa.Float(), nullable=True),
    sa.Column('base_health', sa.Integer(), nullable=True),
    sa.Column('base_health_regen', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('localized_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('roles', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leaguetable',
    sa.Column('leagueid', sa.Integer(), nullable=True),
    sa.Column('tier', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('league_id')
    )
    op.drop_table('pro_matches_id')
    op.add_column('player_hero_histories', sa.Column('hero_id', sa.Integer(), nullable=False))
    op.add_column('player_hero_histories', sa.Column('match_id', sa.BigInteger(), nullable=False))
    op.add_column('player_hero_histories', sa.Column('win', sa.Boolean(), nullable=False))
    op.add_column('player_hero_histories', sa.Column('start_time', sa.Float(), nullable=False))
    op.create_index(op.f('ix_player_hero_histories_start_time'), 'player_hero_histories', ['start_time'], unique=False)
    op.drop_column('player_hero_histories', 'hero_name')
    op.drop_column('player_hero_histories', 'matches')
    op.drop_column('player_hero_histories', 'last_updated')
    op.add_column('team_histories', sa.Column('match_id', sa.BigInteger(), nullable=False))
    op.add_column('team_histories', sa.Column('win', sa.Boolean(), nullable=False))
    op.add_column('team_histories', sa.Column('start_time', sa.Float(), nullable=False))
    op.create_index(op.f('ix_team_histories_start_time'), 'team_histories', ['start_time'], unique=False)
    op.drop_column('team_histories', 'matches')
    op.drop_column('team_histories', 'last_updated')
    op.add_column('team_matchup_histories', sa.Column('match_id', sa.BigInteger(), nullable=False))
    op.add_column('team_matchup_histories', sa.Column('win', sa.Boolean(), nullable=False))
    op.add_column('team_matchup_histories', sa.Column('start_time', sa.Float(), nullable=False))
    op.create_index(op.f('ix_team_matchup_histories_start_time'), 'team_matchup_histories', ['start_time'], unique=False)
    op.drop_column('team_matchup_histories', 'matches')
    op.drop_column('team_matchup_histories', 'last_updated')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_matchup_histories', sa.Column('last_updated', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('team_matchup_histories', sa.Column('matches', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_team_matchup_histories_start_time'), table_name='team_matchup_histories')
    op.drop_column('team_matchup_histories', 'start_time')
    op.drop_column('team_matchup_histories', 'win')
    op.drop_column('team_matchup_histories', 'match_id')
    op.add_column('team_histories', sa.Column('last_updated', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('team_histories', sa.Column('matches', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_team_histories_start_time'), table_name='team_histories')
    op.drop_column('team_histories', 'start_time')
    op.drop_column('team_histories', 'win')
    op.drop_column('team_histories', 'match_id')
    op.add_column('player_hero_histories', sa.Column('last_updated', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('player_hero_histories', sa.Column('matches', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('player_hero_histories', sa.Column('hero_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_player_hero_histories_start_time'), table_name='player_hero_histories')
    op.drop_column('player_hero_histories', 'start_time')
    op.drop_column('player_hero_histories', 'win')
    op.drop_column('player_hero_histories', 'match_id')
    op.drop_column('player_hero_histories', 'hero_id')
    op.create_table('pro_matches_id',
    sa.Column('match_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('match_id', name='pro_matches_id_pkey')
    )
    op.drop_table('leaguetable')
    op.drop_table('herodatatable')
    # ### end Alembic commands ###
