"""Create decayed_state history table for efficient calculation of decay time series features

Revision ID: 8558bbe5548e
Revises: 5d3d6f960198
Create Date: 2025-10-21 03:51:35.272957

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8558bbe5548e"
down_revision: Union[str, None] = "5d3d6f960198"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player_hero_decayed_states",
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("hero_id", sa.Integer(), nullable=False),
        sa.Column("match_id", sa.BigInteger(), nullable=False),
        sa.Column("decayed_wins", sa.Float(), nullable=False),
        sa.Column("decayed_games", sa.Float(), nullable=False),
        sa.Column("last_update_time", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("account_id", "hero_id", "match_id"),
    )
    op.create_table(
        "team_decayed_states",
        sa.Column("team_name", sa.String(), nullable=False),
        sa.Column("match_id", sa.BigInteger(), nullable=False),
        sa.Column("decayed_wins", sa.Float(), nullable=False),
        sa.Column("decayed_games", sa.Float(), nullable=False),
        sa.Column("last_update_time", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("team_name", "match_id"),
    )
    op.create_table(
        "team_matchup_decayed_states",
        sa.Column("team1_name", sa.String(), nullable=False),
        sa.Column("team2_name", sa.String(), nullable=False),
        sa.Column("match_id", sa.BigInteger(), nullable=False),
        sa.Column("decayed_t1_wins", sa.Float(), nullable=False),
        sa.Column("decayed_games", sa.Float(), nullable=False),
        sa.Column("last_update_time", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("team1_name", "team2_name", "match_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("team_matchup_decayed_states")
    op.drop_table("team_decayed_states")
    op.drop_table("player_hero_decayed_states")
    # ### end Alembic commands ###
