"""Changed HeroFeatures hero_picks from Dict to List

Revision ID: 8a4eea8fbd0e
Revises: db6c8916c514
Create Date: 2025-04-05 03:50:33.885037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a4eea8fbd0e'
down_revision: Union[str, None] = 'db6c8916c514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
