"""Update team features table to use flattened structure of 10 columns of hero win rate

Revision ID: 8a798830aad7
Revises: 8558bbe5548e
Create Date: 2025-10-21 07:50:00.334593

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8a798830aad7"
down_revision: Union[str, None] = "8558bbe5548e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Add flattened hero win-rate columns to `hero_features`.

    To avoid NOT NULL violations on existing rows, we add the columns
    with a temporary server default of 0.5 (neutral win rate), which
    backfills existing rows. We then drop the JSON `hero_picks` column
    and remove the server defaults so future inserts must provide values.
    """

    # Add columns with temporary server default for safe backfill
    default = sa.text("0.5")
    op.add_column("hero_features", sa.Column("hero_0_win_rate", sa.Float(), nullable=False, server_default=default))
    op.add_column("hero_features", sa.Column("hero_1_win_rate", sa.Float(), nullable=False, server_default=default))
    op.add_column("hero_features", sa.Column("hero_2_win_rate", sa.Float(), nullable=False, server_default=default))
    op.add_column("hero_features", sa.Column("hero_3_win_rate", sa.Float(), nullable=False, server_default=default))
    op.add_column("hero_features", sa.Column("hero_4_win_rate", sa.Float(), nullable=False, server_default=default))
    op.add_column("hero_features", sa.Column("hero_128_win_rate", sa.Float(), nullable=False, server_default=default))
    op.add_column("hero_features", sa.Column("hero_129_win_rate", sa.Float(), nullable=False, server_default=default))
    op.add_column("hero_features", sa.Column("hero_130_win_rate", sa.Float(), nullable=False, server_default=default))
    op.add_column("hero_features", sa.Column("hero_131_win_rate", sa.Float(), nullable=False, server_default=default))
    op.add_column("hero_features", sa.Column("hero_132_win_rate", sa.Float(), nullable=False, server_default=default))

    # Drop old JSON field after new columns exist
    op.drop_column("hero_features", "hero_picks")

    # Remove server defaults so future inserts must specify concrete values
    for col in [
        "hero_0_win_rate",
        "hero_1_win_rate",
        "hero_2_win_rate",
        "hero_3_win_rate",
        "hero_4_win_rate",
        "hero_128_win_rate",
        "hero_129_win_rate",
        "hero_130_win_rate",
        "hero_131_win_rate",
        "hero_132_win_rate",
    ]:
        op.alter_column("hero_features", col, server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hero_features",
        sa.Column("hero_picks", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    )
    op.drop_column("hero_features", "hero_132_win_rate")
    op.drop_column("hero_features", "hero_131_win_rate")
    op.drop_column("hero_features", "hero_130_win_rate")
    op.drop_column("hero_features", "hero_129_win_rate")
    op.drop_column("hero_features", "hero_128_win_rate")
    op.drop_column("hero_features", "hero_4_win_rate")
    op.drop_column("hero_features", "hero_3_win_rate")
    op.drop_column("hero_features", "hero_2_win_rate")
    op.drop_column("hero_features", "hero_1_win_rate")
    op.drop_column("hero_features", "hero_0_win_rate")
    # ### end Alembic commands ###
