"""change optional fields to mandatory in MatchTable and MatchOutcomeTable

Revision ID: 90573f54f27b
Revises: 27d2c9fe590a
Create Date: 2025-05-28 12:07:30.615903

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "90573f54f27b"
down_revision: Union[str, None] = "27d2c9fe590a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Delete rows with NULL hero_ids (any slot with NULL hero_id)

    # Drop existing constraints
    op.execute("ALTER TABLE hero_features DROP CONSTRAINT hero_features_match_id_fkey")
    op.execute("ALTER TABLE player_hero_features DROP CONSTRAINT player_hero_features_match_id_fkey")
    op.execute("ALTER TABLE team_features DROP CONSTRAINT team_features_match_id_fkey")

    # Add them back with CASCADE
    op.execute(
        """
        ALTER TABLE hero_features
        ADD CONSTRAINT hero_features_match_id_fkey
        FOREIGN KEY (match_id) REFERENCES matches(match_id) ON DELETE CASCADE
    """
    )
    op.execute(
        """
        ALTER TABLE player_hero_features
        ADD CONSTRAINT player_hero_features_match_id_fkey
        FOREIGN KEY (match_id) REFERENCES matches(match_id) ON DELETE CASCADE
    """
    )
    op.execute(
        """
        ALTER TABLE team_features
        ADD CONSTRAINT team_features_match_id_fkey
        FOREIGN KEY (match_id) REFERENCES matches(match_id) ON DELETE CASCADE
    """
    )

    op.execute(
        """
        DELETE FROM matches
        WHERE slot_0_hero_id IS NULL
           OR slot_1_hero_id IS NULL
           OR slot_2_hero_id IS NULL
           OR slot_3_hero_id IS NULL
           OR slot_4_hero_id IS NULL
           OR slot_128_hero_id IS NULL
           OR slot_129_hero_id IS NULL
           OR slot_130_hero_id IS NULL
           OR slot_131_hero_id IS NULL
           OR slot_132_hero_id IS NULL
    """
    )

    op.execute(
        """
        DELETE FROM matches
        WHERE slot_0_account_id IS NULL
           OR slot_1_account_id IS NULL
           OR slot_2_account_id IS NULL
           OR slot_3_account_id IS NULL
           OR slot_4_account_id IS NULL
           OR slot_128_account_id IS NULL
           OR slot_129_account_id IS NULL
           OR slot_130_account_id IS NULL
           OR slot_131_account_id IS NULL
           OR slot_132_account_id IS NULL
    """
    )

    # Delete rows with NULL team_ids and start_time
    op.execute("DELETE FROM matches WHERE radiant_team_id IS NULL OR dire_team_id IS NULL OR start_time IS NULL")

    # Delete rows with NULL radiant_win
    op.execute("DELETE FROM match_outcomes WHERE radiant_win IS NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("match_outcomes", "radiant_win", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("matches", "slot_0_hero_id", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("matches", "slot_1_hero_id", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("matches", "slot_2_hero_id", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("matches", "slot_3_hero_id", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("matches", "slot_4_hero_id", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("matches", "slot_128_hero_id", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("matches", "slot_129_hero_id", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("matches", "slot_130_hero_id", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("matches", "slot_131_hero_id", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("matches", "slot_132_hero_id", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("matches", "slot_0_account_id", existing_type=sa.BIGINT(), nullable=False)
    op.alter_column("matches", "slot_1_account_id", existing_type=sa.BIGINT(), nullable=False)
    op.alter_column("matches", "slot_2_account_id", existing_type=sa.BIGINT(), nullable=False)
    op.alter_column("matches", "slot_3_account_id", existing_type=sa.BIGINT(), nullable=False)
    op.alter_column("matches", "slot_4_account_id", existing_type=sa.BIGINT(), nullable=False)
    op.alter_column("matches", "slot_128_account_id", existing_type=sa.BIGINT(), nullable=False)
    op.alter_column("matches", "slot_129_account_id", existing_type=sa.BIGINT(), nullable=False)
    op.alter_column("matches", "slot_130_account_id", existing_type=sa.BIGINT(), nullable=False)
    op.alter_column("matches", "slot_131_account_id", existing_type=sa.BIGINT(), nullable=False)
    op.alter_column("matches", "slot_132_account_id", existing_type=sa.BIGINT(), nullable=False)
    op.alter_column("matches", "radiant_team_id", existing_type=sa.BIGINT(), nullable=False)
    op.alter_column("matches", "dire_team_id", existing_type=sa.BIGINT(), nullable=False)
    op.alter_column("matches", "start_time", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Restore original foreign key constraints (without CASCADE if that was the original setup)
    op.execute("ALTER TABLE hero_features DROP CONSTRAINT hero_features_match_id_fkey")
    op.execute("ALTER TABLE player_hero_features DROP CONSTRAINT player_hero_features_match_id_fkey")
    op.execute("ALTER TABLE team_features DROP CONSTRAINT team_features_match_id_fkey")

    op.execute(
        """
        ALTER TABLE hero_features
        ADD CONSTRAINT hero_features_match_id_fkey
        FOREIGN KEY (match_id) REFERENCES matches(match_id)
    """
    )
    op.execute(
        """
        ALTER TABLE player_hero_features
        ADD CONSTRAINT player_hero_features_match_id_fkey
        FOREIGN KEY (match_id) REFERENCES matches(match_id)
    """
    )
    op.execute(
        """
        ALTER TABLE team_features
        ADD CONSTRAINT team_features_match_id_fkey
        FOREIGN KEY (match_id) REFERENCES matches(match_id)
    """
    )

    op.alter_column("matches", "start_time", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True)
    op.alter_column("matches", "dire_team_id", existing_type=sa.BIGINT(), nullable=True)
    op.alter_column("matches", "radiant_team_id", existing_type=sa.BIGINT(), nullable=True)
    op.alter_column("matches", "slot_132_account_id", existing_type=sa.BIGINT(), nullable=True)
    op.alter_column("matches", "slot_131_account_id", existing_type=sa.BIGINT(), nullable=True)
    op.alter_column("matches", "slot_130_account_id", existing_type=sa.BIGINT(), nullable=True)
    op.alter_column("matches", "slot_129_account_id", existing_type=sa.BIGINT(), nullable=True)
    op.alter_column("matches", "slot_128_account_id", existing_type=sa.BIGINT(), nullable=True)
    op.alter_column("matches", "slot_4_account_id", existing_type=sa.BIGINT(), nullable=True)
    op.alter_column("matches", "slot_3_account_id", existing_type=sa.BIGINT(), nullable=True)
    op.alter_column("matches", "slot_2_account_id", existing_type=sa.BIGINT(), nullable=True)
    op.alter_column("matches", "slot_1_account_id", existing_type=sa.BIGINT(), nullable=True)
    op.alter_column("matches", "slot_0_account_id", existing_type=sa.BIGINT(), nullable=True)
    op.alter_column("matches", "slot_132_hero_id", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("matches", "slot_131_hero_id", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("matches", "slot_130_hero_id", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("matches", "slot_129_hero_id", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("matches", "slot_128_hero_id", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("matches", "slot_4_hero_id", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("matches", "slot_3_hero_id", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("matches", "slot_2_hero_id", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("matches", "slot_1_hero_id", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("matches", "slot_0_hero_id", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("match_outcomes", "radiant_win", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###
