"""added tablename for playerherofeature

Revision ID: a2c5bfa13ae4
Revises: 677e4c99eee5
Create Date: 2025-04-07 03:27:41.630399

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a2c5bfa13ae4"
down_revision: Union[str, None] = "677e4c99eee5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player_hero_features",
        sa.Column("match_id", sa.BigInteger(), nullable=False),
        sa.Column("player_hero_0_win_rate", sa.Float(), nullable=False),
        sa.Column("player_hero_1_win_rate", sa.Float(), nullable=False),
        sa.Column("player_hero_2_win_rate", sa.Float(), nullable=False),
        sa.Column("player_hero_3_win_rate", sa.Float(), nullable=False),
        sa.Column("player_hero_4_win_rate", sa.Float(), nullable=False),
        sa.Column("player_hero_128_win_rate", sa.Float(), nullable=False),
        sa.Column("player_hero_129_win_rate", sa.Float(), nullable=False),
        sa.Column("player_hero_130_win_rate", sa.Float(), nullable=False),
        sa.Column("player_hero_131_win_rate", sa.Float(), nullable=False),
        sa.Column("player_hero_132_win_rate", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["pro_matches.match_id"],
        ),
        sa.PrimaryKeyConstraint("match_id"),
    )
    op.drop_table("playerherofeature")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "playerherofeature",
        sa.Column("match_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("player_hero_0_win_rate", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
        sa.Column("player_hero_1_win_rate", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
        sa.Column("player_hero_2_win_rate", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
        sa.Column("player_hero_3_win_rate", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
        sa.Column("player_hero_4_win_rate", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
        sa.Column("player_hero_128_win_rate", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
        sa.Column("player_hero_129_win_rate", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
        sa.Column("player_hero_130_win_rate", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
        sa.Column("player_hero_131_win_rate", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
        sa.Column("player_hero_132_win_rate", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["match_id"], ["pro_matches.match_id"], name="playerherofeature_match_id_fkey"),
        sa.PrimaryKeyConstraint("match_id", name="playerherofeature_pkey"),
    )
    op.drop_table("player_hero_features")
    # ### end Alembic commands ###
