"""add public_matches table

Revision ID: a431fe3a81a0
Revises: 251d60043abf
Create Date: 2025-09-23 12:13:27.350372

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a431fe3a81a0"
down_revision: Union[str, None] = "251d60043abf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "public_matches",
        sa.Column("match_id", sa.BigInteger(), nullable=False),
        sa.Column("start_time", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("avg_rank_tier", sa.Integer(), nullable=False),
        sa.Column("num_rank_tier", sa.Integer(), nullable=False),
        sa.Column("radiant_win", sa.Boolean(), nullable=False),
        sa.Column("slot_0_hero_id", sa.Integer(), nullable=False),
        sa.Column("slot_1_hero_id", sa.Integer(), nullable=False),
        sa.Column("slot_2_hero_id", sa.Integer(), nullable=False),
        sa.Column("slot_3_hero_id", sa.Integer(), nullable=False),
        sa.Column("slot_4_hero_id", sa.Integer(), nullable=False),
        sa.Column("slot_128_hero_id", sa.Integer(), nullable=False),
        sa.Column("slot_129_hero_id", sa.Integer(), nullable=False),
        sa.Column("slot_130_hero_id", sa.Integer(), nullable=False),
        sa.Column("slot_131_hero_id", sa.Integer(), nullable=False),
        sa.Column("slot_132_hero_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("match_id"),
    )
    op.create_index("ix_public_matches_start_time", "public_matches", ["start_time"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_public_matches_start_time", table_name="public_matches")
    op.drop_table("public_matches")
    # ### end Alembic commands ###
