"""Add HeroDecayedStateTable

Revision ID: ae330bf4787a
Revises: 8a798830aad7
Create Date: 2025-10-31 07:18:33.969298

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ae330bf4787a"
down_revision: Union[str, None] = "8a798830aad7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hero_decayed_states",
        sa.Column("hero_id", sa.Integer(), nullable=False),
        sa.Column("match_id", sa.BigInteger(), nullable=False),
        sa.Column("decayed_wins", sa.Float(), nullable=False),
        sa.Column("decayed_games", sa.Float(), nullable=False),
        sa.Column("last_update_time", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("hero_id", "match_id"),
    )
    op.drop_index(op.f("ix_team_matchup_histories_start_time"), table_name="team_matchup_histories")
    op.drop_table("team_matchup_histories")
    op.drop_index(op.f("ix_team_histories_start_time"), table_name="team_histories")
    op.drop_table("team_histories")
    op.drop_index(op.f("ix_player_hero_histories_start_time"), table_name="player_hero_histories")
    op.drop_table("player_hero_histories")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player_hero_histories",
        sa.Column("account_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("hero_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("match_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("win", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("start_time", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("account_id", "hero_id", "match_id", name=op.f("player_hero_histories_pkey")),
    )
    op.create_index(op.f("ix_player_hero_histories_start_time"), "player_hero_histories", ["start_time"], unique=False)
    op.create_table(
        "team_histories",
        sa.Column("team_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("match_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("win", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("start_time", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("team_name", "match_id", name=op.f("team_histories_pkey")),
    )
    op.create_index(op.f("ix_team_histories_start_time"), "team_histories", ["start_time"], unique=False)
    op.create_table(
        "team_matchup_histories",
        sa.Column("team1_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("team2_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("match_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("win", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("start_time", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("team1_name", "team2_name", "match_id", name=op.f("pk_team_matchup_histories")),
    )
    op.create_index(
        op.f("ix_team_matchup_histories_start_time"), "team_matchup_histories", ["start_time"], unique=False
    )
    op.drop_table("hero_decayed_states")
    # ### end Alembic commands ###
