"""Changed ProMatch table to Match, table name to matches. Added MatchOutcome:outcomes Table with radiant_win field transfered from matches table to outcomes table.

Revision ID: bb8cf55dfcc3
Revises: e57c3f5cac77
Create Date: 2025-04-23 09:40:46.017052

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy import text
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "bb8cf55dfcc3"
down_revision: Union[str, None] = "e57c3f5cac77"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "matches",
        sa.Column("match_id", sa.BigInteger(), nullable=False),
        sa.Column("slot_0_hero_id", sa.Float(), nullable=True),
        sa.Column("slot_1_hero_id", sa.Float(), nullable=True),
        sa.Column("slot_2_hero_id", sa.Float(), nullable=True),
        sa.Column("slot_3_hero_id", sa.Float(), nullable=True),
        sa.Column("slot_4_hero_id", sa.Float(), nullable=True),
        sa.Column("slot_128_hero_id", sa.Float(), nullable=True),
        sa.Column("slot_129_hero_id", sa.Float(), nullable=True),
        sa.Column("slot_130_hero_id", sa.Float(), nullable=True),
        sa.Column("slot_131_hero_id", sa.Float(), nullable=True),
        sa.Column("slot_132_hero_id", sa.Float(), nullable=True),
        sa.Column("slot_0_account_id", sa.Float(), nullable=True),
        sa.Column("slot_1_account_id", sa.Float(), nullable=True),
        sa.Column("slot_2_account_id", sa.Float(), nullable=True),
        sa.Column("slot_3_account_id", sa.Float(), nullable=True),
        sa.Column("slot_4_account_id", sa.Float(), nullable=True),
        sa.Column("slot_128_account_id", sa.Float(), nullable=True),
        sa.Column("slot_129_account_id", sa.Float(), nullable=True),
        sa.Column("slot_130_account_id", sa.Float(), nullable=True),
        sa.Column("slot_131_account_id", sa.Float(), nullable=True),
        sa.Column("slot_132_account_id", sa.Float(), nullable=True),
        sa.Column("radiant_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("radiant_team_id", sa.Float(), nullable=True),
        sa.Column("dire_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("dire_team_id", sa.Float(), nullable=True),
        sa.Column("start_time", sa.Float(), nullable=True),
        sa.Column("duration", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("match_id"),
    )

    op.create_table(
        "match_outcomes",
        sa.Column("match_id", sa.BigInteger(), nullable=False),
        sa.Column("radiant_win", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.match_id"],
        ),
        sa.PrimaryKeyConstraint("match_id"),
    )

    # Data Migration Logic
    conn = op.get_bind()

    # First check if the pro_matches table exists
    inspector = sa.inspect(conn)
    if "pro_matches" in inspector.get_table_names():
        # Get column names from pro_matches to determine what to transfer
        columns = [c["name"] for c in inspector.get_columns("pro_matches")]

        # Build a map of columns from pro_matches that match matches table
        match_columns = []
        for column in columns:
            if column != "radiant_win" and column in [
                "match_id",
                "slot_0_hero_id",
                "slot_1_hero_id",
                "slot_2_hero_id",
                "slot_3_hero_id",
                "slot_4_hero_id",
                "slot_128_hero_id",
                "slot_129_hero_id",
                "slot_130_hero_id",
                "slot_131_hero_id",
                "slot_132_hero_id",
                "slot_0_account_id",
                "slot_1_account_id",
                "slot_2_account_id",
                "slot_3_account_id",
                "slot_4_account_id",
                "slot_128_account_id",
                "slot_129_account_id",
                "slot_130_account_id",
                "slot_131_account_id",
                "slot_132_account_id",
                "radiant_name",
                "radiant_team_id",
                "dire_name",
                "dire_team_id",
                "start_time",
                "duration",
            ]:
                match_columns.append(column)

        # Dynamically build the SELECT statement for matches data
        select_columns_str = ", ".join(match_columns)

        # Transfer data to matches table - use text() to create SQL expression
        insert_sql = text(
            f"""
            INSERT INTO matches ({select_columns_str})
            SELECT {select_columns_str} FROM pro_matches
            ON CONFLICT (match_id) DO NOTHING
        """
        )
        conn.execute(insert_sql)

        # Transfer radiant_win data to match_outcomes if it exists
        if "radiant_win" in columns:
            outcome_sql = text(
                """
                INSERT INTO match_outcomes (match_id, radiant_win)
                SELECT match_id, radiant_win FROM pro_matches
                WHERE radiant_win IS NOT NULL
                ON CONFLICT (match_id) DO NOTHING
            """
            )
            conn.execute(outcome_sql)

    op.drop_constraint("hero_features_match_id_fkey", "hero_features", type_="foreignkey")
    op.create_foreign_key(None, "hero_features", "matches", ["match_id"], ["match_id"])
    op.create_foreign_key(None, "match_predictions", "matches", ["match_id"], ["match_id"])
    op.drop_constraint("player_hero_features_match_id_fkey", "player_hero_features", type_="foreignkey")
    op.create_foreign_key(None, "player_hero_features", "matches", ["match_id"], ["match_id"])
    op.drop_constraint("team_features_match_id_fkey", "team_features", type_="foreignkey")
    op.create_foreign_key(None, "team_features", "matches", ["match_id"], ["match_id"])
    # ### end Alembic commands ###

    op.drop_table("pro_matches")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "team_features", type_="foreignkey")
    op.create_foreign_key("team_features_match_id_fkey", "team_features", "pro_matches", ["match_id"], ["match_id"])
    op.drop_constraint(None, "player_hero_features", type_="foreignkey")
    op.create_foreign_key(
        "player_hero_features_match_id_fkey", "player_hero_features", "pro_matches", ["match_id"], ["match_id"]
    )
    op.drop_constraint(None, "match_predictions", type_="foreignkey")
    op.drop_constraint(None, "hero_features", type_="foreignkey")
    op.create_foreign_key("hero_features_match_id_fkey", "hero_features", "pro_matches", ["match_id"], ["match_id"])
    op.create_table(
        "pro_matches",
        sa.Column("radiant_name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("radiant_team_id", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("dire_name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("dire_team_id", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("start_time", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("duration", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("radiant_win", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("match_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("slot_0_hero_id", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("slot_1_hero_id", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("slot_2_hero_id", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("slot_3_hero_id", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("slot_4_hero_id", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("slot_128_hero_id", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("slot_129_hero_id", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("slot_130_hero_id", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("slot_131_hero_id", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("slot_132_hero_id", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("slot_0_account_id", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("slot_1_account_id", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("slot_2_account_id", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("slot_3_account_id", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("slot_4_account_id", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("slot_128_account_id", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("slot_129_account_id", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("slot_130_account_id", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("slot_131_account_id", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("slot_132_account_id", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.UniqueConstraint("match_id", name="unique_match_id_constraint"),
    )
    op.drop_table("match_outcomes")
    op.drop_table("matches")
    # ### end Alembic commands ###
