"""add foreign key constraint

Revision ID: d582735221b4
Revises: 108a45b0cd5e
Create Date: 2025-06-01 01:54:09.589006

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'd582735221b4'
down_revision: Union[str, None] = '108a45b0cd5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
        DELETE FROM match_outcomes 
        WHERE match_id NOT IN (SELECT match_id FROM matches)
    """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'match_outcomes', 'matches', ['match_id'], ['match_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'match_outcomes', type_='foreignkey')
    # ### end Alembic commands ###
