"""Added HeroFeatures Table

Revision ID: db6c8916c514
Revises: f77298ade4ed
Create Date: 2025-04-05 03:13:58.718131

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "db6c8916c514"
down_revision: Union[str, None] = "f77298ade4ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hero_features",
        sa.Column("match_id", sa.BigInteger(), nullable=False),
        sa.Column("hero_picks", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["pro_matches.match_id"],
        ),
        sa.PrimaryKeyConstraint("match_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("hero_features")
    # ### end Alembic commands ###
