"""Added MatchPrediction Table

Revision ID: e57c3f5cac77
Revises: 3c1102fc4b5c
Create Date: 2025-04-22 03:50:29.327570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e57c3f5cac77'
down_revision: Union[str, None] = '3c1102fc4b5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_predictions',
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('prediction', sa.Boolean(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prediction_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('match_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_predictions')
    # ### end Alembic commands ###
