export const tabledata = [
    { time: "2024-08-07 10:00", model_prediction: "Radiant", outcome: "Dire", radiant: "Radiant Team", dire: "Dire Team", tournament: "Summer Cup" },
    { time: "2024-08-07 12:00", model_prediction: "Dire", outcome: "Radiant", radiant: "Radiant Team", dire: "Dire Team", tournament: "Winter Cup" },
    { time: "2024-08-08 14:00", model_prediction: "Radiant", outcome: "Radiant", radiant: "Radiant Team", dire: "Dire Team", tournament: "Autumn Cup" },
    { time: "2024-08-09 16:00", model_prediction: "Dire", outcome: "Dire", radiant: "Radiant Team", dire: "Dire Team", tournament: "Spring Cup" },
    { time: "2024-08-10 18:00", model_prediction: "Radiant", outcome: "Dire", radiant: "Radiant Team", dire: "Dire Team", tournament: "Summer Cup" },
    { time: "2024-08-11 20:00", model_prediction: "Dire", outcome: "Radiant", radiant: "Radiant Team", dire: "Dire Team", tournament: "Winter Cup" },
    { time: "2024-08-12 10:00", model_prediction: "Radiant", outcome: "Radiant", radiant: "Radiant Team", dire: "Dire Team", tournament: "Autumn Cup" },
    { time: "2024-08-13 12:00", model_prediction: "Dire", outcome: "Dire", radiant: "Radiant Team", dire: "Dire Team", tournament: "Spring Cup" },
    { time: "2024-08-14 14:00", model_prediction: "Radiant", outcome: "Dire", radiant: "Radiant Team", dire: "Dire Team", tournament: "Summer Cup" },
    { time: "2024-08-15 16:00", model_prediction: "Dire", outcome: "Radiant", radiant: "Radiant Team", dire: "Dire Team", tournament: "Winter Cup" },
    { time: "2024-08-16 18:00", model_prediction: "Radiant", outcome: "Radiant", radiant: "Radiant Team", dire: "Dire Team", tournament: "Autumn Cup" },
    { time: "2024-08-17 20:00", model_prediction: "Dire", outcome: "Dire", radiant: "Radiant Team", dire: "Dire Team", tournament: "Spring Cup" },
    { time: "2024-08-18 10:00", model_prediction: "Radiant", outcome: "Dire", radiant: "Radiant Team", dire: "Dire Team", tournament: "Summer Cup" },
    { time: "2024-08-19 12:00", model_prediction: "Dire", outcome: "Radiant", radiant: "Radiant Team", dire: "Dire Team", tournament: "Winter Cup" },
    { time: "2024-08-20 14:00", model_prediction: "Radiant", outcome: "Radiant", radiant: "Radiant Team", dire: "Dire Team", tournament: "Autumn Cup" },
    { time: "2024-08-21 16:00", model_prediction: "Dire", outcome: "Dire", radiant: "Radiant Team", dire: "Dire Team", tournament: "Spring Cup" },
    { time: "2024-08-22 18:00", model_prediction: "Radiant", outcome: "Dire", radiant: "Radiant Team", dire: "Dire Team", tournament: "Summer Cup" },
    { time: "2024-08-23 20:00", model_prediction: "Dire", outcome: "Radiant", radiant: "Radiant Team", dire: "Dire Team", tournament: "Winter Cup" },
    { time: "2024-08-24 10:00", model_prediction: "Radiant", outcome: "Radiant", radiant: "Radiant Team", dire: "Dire Team", tournament: "Autumn Cup" },
    { time: "2024-08-25 12:00", model_prediction: "Dire", outcome: "Dire", radiant: "Radiant Team", dire: "Dire Team", tournament: "Spring Cup" },
  ];
  