"""Added table: TeamFeatures (team_features)

Revision ID: 47051f1a4ac8
Revises: 3151fde5447f
Create Date: 2025-04-04 09:38:16.609318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47051f1a4ac8'
down_revision: Union[str, None] = '3151fde5447f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_features',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('radiant_dire_matchup', sa.Float(), nullable=False),
    sa.Column('radiant_win_rate', sa.Float(), nullable=False),
    sa.Column('dire_win_rate', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['pro_matches.match_id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_features')
    # ### end Alembic commands ###
