"""added team_histories tables to database

Revision ID: ac9fd55058d7
Revises: a2c5bfa13ae4
Create Date: 2025-04-08 10:56:24.293806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac9fd55058d7'
down_revision: Union[str, None] = 'a2c5bfa13ae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_hero_histories',
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('hero_name', sa.String(), nullable=False),
    sa.Column('matches', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('account_id', 'hero_name')
    )
    op.create_table('team_histories',
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('matches', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('team_name')
    )
    op.create_table('team_matchup_histories',
    sa.Column('team1_name', sa.String(), nullable=False),
    sa.Column('team2_name', sa.String(), nullable=False),
    sa.Column('matches', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('team1_name', 'team2_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_matchup_histories')
    op.drop_table('team_histories')
    op.drop_table('player_hero_histories')
    # ### end Alembic commands ###
