/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/inference/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Predict match outcome based on hero picks */
        post: operations["predict_inference_predict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inference/model_history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * get model performance history
         * @description Get model performance history.
         *
         *     Returns:
         *         ModelHistoryResponse: The model performance history.
         */
        get: operations["get_model_history_inference_model_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Matches
         * @description Get paginated matches with optional filters.
         *
         *     Returns completed matches in descending order of match ID (latest first).
         *     You can filter by hero names, patch numbers, and team names.
         */
        get: operations["get_matches_matches__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/streaming/live-state-update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish messages from streaming backend */
        post: operations["post_live_state_update_streaming_live_state_update_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/streaming/sse/live_matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Subscriber's Gateway for SSE
         * @description Establishes an SSE connection. The client will receive updates
         *     pushed from the /live-state-update endpoint via Redis Pub/Sub.
         */
        get: operations["get_live_state_sse_streaming_sse_live_matches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/heroes/get_image_urls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get hero image URLs - HOT RELOAD TEST */
        get: operations["get_hero_image_urls_heroes_get_image_urls_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patches/ids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get list of available patch identifiers */
        get: operations["get_patch_ids_patches_ids_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leagues/get_league_info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get league information */
        get: operations["get_league_info_leagues_get_league_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AggregateBy
         * @enum {integer}
         */
        AggregateBy: 1 | 7 | 30;
        /**
         * CompletedMatchAPIPayload
         * @description Completed Match with predictions and actual outcome
         *     Inherits from Match with Outcome and add prediction results
         */
        CompletedMatchAPIPayload: {
            /** Match Id */
            match_id: number;
            /** Leagueid */
            leagueid?: number | null;
            /** Radiant Name */
            radiant_name?: string | null;
            /** Radiant Team Id */
            radiant_team_id: number;
            /** Dire Name */
            dire_name?: string | null;
            /** Dire Team Id */
            dire_team_id: number;
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /** Duration */
            duration?: number | null;
            /** Slot 0 Hero Id */
            slot_0_hero_id: number;
            /** Slot 1 Hero Id */
            slot_1_hero_id: number;
            /** Slot 2 Hero Id */
            slot_2_hero_id: number;
            /** Slot 3 Hero Id */
            slot_3_hero_id: number;
            /** Slot 4 Hero Id */
            slot_4_hero_id: number;
            /** Slot 128 Hero Id */
            slot_128_hero_id: number;
            /** Slot 129 Hero Id */
            slot_129_hero_id: number;
            /** Slot 130 Hero Id */
            slot_130_hero_id: number;
            /** Slot 131 Hero Id */
            slot_131_hero_id: number;
            /** Slot 132 Hero Id */
            slot_132_hero_id: number;
            /** Slot 0 Account Id */
            slot_0_account_id: number;
            /** Slot 1 Account Id */
            slot_1_account_id: number;
            /** Slot 2 Account Id */
            slot_2_account_id: number;
            /** Slot 3 Account Id */
            slot_3_account_id: number;
            /** Slot 4 Account Id */
            slot_4_account_id: number;
            /** Slot 128 Account Id */
            slot_128_account_id: number;
            /** Slot 129 Account Id */
            slot_129_account_id: number;
            /** Slot 130 Account Id */
            slot_130_account_id: number;
            /** Slot 131 Account Id */
            slot_131_account_id: number;
            /** Slot 132 Account Id */
            slot_132_account_id: number;
            /** Radiant Win */
            radiant_win: boolean;
            /** Predicted Outcome */
            predicted_outcome?: boolean | null;
            league_data?: components["schemas"]["dota_oracle_common__models__match__schema__LeagueData"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeroImageData */
        HeroImageData: {
            /** Hero Id */
            hero_id: number;
            /** Hero Name */
            hero_name: string;
            /** Image Url */
            image_url?: string | null;
            /** Icon Url */
            icon_url?: string | null;
            /** Primary Attr */
            primary_attr?: string | null;
        };
        /** HeroImageResponse */
        HeroImageResponse: {
            /** Heroes */
            heroes: components["schemas"]["HeroImageData"][];
        };
        /**
         * HistoryRange
         * @enum {integer}
         */
        HistoryRange: 7 | 30 | 90 | 365 | 0;
        /**
         * LeagueData
         * @description League information for matches.
         *
         *     Attributes:
         *         leagueid: League identifier (Optional[int])
         *         tier: League tier level (Optional[str])
         *         name: League display name (Optional[str])
         */
        "LeagueData-Input": {
            /** Leagueid */
            leagueid?: number | null;
            /** Tier */
            tier?: string | null;
            /** Name */
            name?: string | null;
        };
        /** LeagueDataResponse */
        LeagueDataResponse: {
            /** Leagues */
            leagues: components["schemas"]["dota_oracle_common__models__api__schema__LeagueData"][];
        };
        /** LiveStateUpdateRequest */
        LiveStateUpdateRequest: {
            /** Live Matches */
            live_matches: components["schemas"]["MatchNotifcationAPIPayload"][];
        };
        /**
         * MatchNotifcationAPIPayload
         * @description Match model combined with prediction data.
         *
         *     Inherits from Match and adds prediciton result
         *
         *     Attributes:
         *         model_prediction: predicted outcome for the match
         */
        MatchNotifcationAPIPayload: {
            /** Match Id */
            match_id: number;
            /** Leagueid */
            leagueid?: number | null;
            /** Radiant Name */
            radiant_name?: string | null;
            /** Radiant Team Id */
            radiant_team_id: number;
            /** Dire Name */
            dire_name?: string | null;
            /** Dire Team Id */
            dire_team_id: number;
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /** Duration */
            duration?: number | null;
            /** Slot 0 Hero Id */
            slot_0_hero_id: number;
            /** Slot 1 Hero Id */
            slot_1_hero_id: number;
            /** Slot 2 Hero Id */
            slot_2_hero_id: number;
            /** Slot 3 Hero Id */
            slot_3_hero_id: number;
            /** Slot 4 Hero Id */
            slot_4_hero_id: number;
            /** Slot 128 Hero Id */
            slot_128_hero_id: number;
            /** Slot 129 Hero Id */
            slot_129_hero_id: number;
            /** Slot 130 Hero Id */
            slot_130_hero_id: number;
            /** Slot 131 Hero Id */
            slot_131_hero_id: number;
            /** Slot 132 Hero Id */
            slot_132_hero_id: number;
            /** Slot 0 Account Id */
            slot_0_account_id: number;
            /** Slot 1 Account Id */
            slot_1_account_id: number;
            /** Slot 2 Account Id */
            slot_2_account_id: number;
            /** Slot 3 Account Id */
            slot_3_account_id: number;
            /** Slot 4 Account Id */
            slot_4_account_id: number;
            /** Slot 128 Account Id */
            slot_128_account_id: number;
            /** Slot 129 Account Id */
            slot_129_account_id: number;
            /** Slot 130 Account Id */
            slot_130_account_id: number;
            /** Slot 131 Account Id */
            slot_131_account_id: number;
            /** Slot 132 Account Id */
            slot_132_account_id: number;
            /** Predicted Outcome */
            predicted_outcome?: boolean | null;
            league_data?: components["schemas"]["LeagueData-Input"] | null;
        };
        /** ModelHistoryResponse */
        ModelHistoryResponse: {
            /** History */
            history: components["schemas"]["ModelPerformanceEntry"][];
        };
        /** ModelPerformanceEntry */
        ModelPerformanceEntry: {
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /** Accuracy */
            accuracy: number;
            /** Log Loss */
            log_loss?: number | null;
            /** Precision */
            precision?: number | null;
            /** Recall */
            recall?: number | null;
        };
        /**
         * PaginatedMatchResponse
         * @description Response model for paginated matches
         */
        PaginatedMatchResponse: {
            /** Matches */
            matches: components["schemas"]["CompletedMatchAPIPayload"][];
            /** Total Count */
            total_count: number;
            /** Total Pages */
            total_pages: number;
            /** Page */
            page?: number | null;
            /** Page Size */
            page_size?: number | null;
            /** Has Next */
            has_next?: boolean | null;
            /** Has Previous */
            has_previous?: boolean | null;
        };
        /**
         * PatchDataAPIResponse
         * @description API response model for available patch identifiers.
         */
        PatchDataAPIResponse: {
            /**
             * Patches
             * @default []
             */
            patches: string[];
        };
        /** PublicMatchPredictionRequest */
        PublicMatchPredictionRequest: {
            /** Radiant Hero Id 1 */
            radiant_hero_id_1: number;
            /** Radiant Hero Id 2 */
            radiant_hero_id_2: number;
            /** Radiant Hero Id 3 */
            radiant_hero_id_3: number;
            /** Radiant Hero Id 4 */
            radiant_hero_id_4: number;
            /** Radiant Hero Id 5 */
            radiant_hero_id_5: number;
            /** Dire Hero Id 1 */
            dire_hero_id_1: number;
            /** Dire Hero Id 2 */
            dire_hero_id_2: number;
            /** Dire Hero Id 3 */
            dire_hero_id_3: number;
            /** Dire Hero Id 4 */
            dire_hero_id_4: number;
            /** Dire Hero Id 5 */
            dire_hero_id_5: number;
        };
        /** PublicMatchPredictionResponse */
        PublicMatchPredictionResponse: {
            /** Prediction */
            prediction: boolean;
            /** Probability */
            probability: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** LeagueData */
        dota_oracle_common__models__api__schema__LeagueData: {
            /** Leagueid */
            leagueid: number;
            /** Tier */
            tier?: string | null;
            /** Name */
            name?: string | null;
        };
        /**
         * LeagueData
         * @description League information for matches.
         *
         *     Attributes:
         *         leagueid: League identifier (Optional[int])
         *         tier: League tier level (Optional[str])
         *         name: League display name (Optional[str])
         */
        dota_oracle_common__models__match__schema__LeagueData: {
            /** Leagueid */
            leagueid?: number | null;
            /** Tier */
            tier?: string | null;
            /** Name */
            name?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    predict_inference_predict_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublicMatchPredictionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicMatchPredictionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_model_history_inference_model_history_get: {
        parameters: {
            query: {
                history_range: components["schemas"]["HistoryRange"];
                aggregate_by: components["schemas"]["AggregateBy"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_matches_matches__get: {
        parameters: {
            query?: {
                /** @description Page number (1-indexed) - Legacy, use offset/limit instead */
                page?: number | null;
                /** @description Items per page (10-50) - Legacy, use offset/limit instead */
                page_size?: number | null;
                /** @description Offset for pagination (alternative to page), 0-indexed */
                offset?: number | null;
                /** @description Limit for pagination (alternative to page_size), 0-50 */
                limit?: number | null;
                /** @description Filter by specific match ID */
                match_id?: number | null;
                /** @description Filter by patch number (e.g., '7.35') */
                patch_number?: string | null;
                /** @description Filter by team name (partial match) */
                team_name?: string | null;
                /** @description Filter by league ID (exact match) */
                league_id?: number | null;
                /** @description Filter by a list of team IDs */
                "team_ids[]"?: number[] | null;
                /** @description Filter by a list of hero IDs */
                "hero_ids[]"?: number[] | null;
                patch_start_time?: string | null;
                patch_end_time?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_live_state_update_streaming_live_state_update_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LiveStateUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Streaming endpoint not available */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_live_state_sse_streaming_sse_live_matches_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Streaming endpoint not available */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_hero_image_urls_heroes_get_image_urls_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeroImageResponse"];
                };
            };
        };
    };
    get_patch_ids_patches_ids_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatchDataAPIResponse"];
                };
            };
        };
    };
    get_league_info_leagues_get_league_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeagueDataResponse"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
